
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd build
  - cd Debug
  - ./Test