
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.2 
      env:
        - CONFIGURATION=Debug
        - CONFIGURATION=Release
script:
  - mkdir build
  - cd build
  - cmake -G Xcode ..
  - cmake --build . --config $CONFIGURATION
  - cd build/$CONFIGURATION
  - ./Test
